routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PrincipalController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PrincipalController::class, 'principalBaterias'])->name('/');

Route::get('/teoria', [PrincipalController::class, 'teoria'])->name('teoria');

Route::get('/procedimento', [PrincipalController::class, 'procedimento'])->name('procedimento');

Route::get('/medicoes', [PrincipalController::class, 'medicoes'])->name('medicoes');

Route::get('/conclusoes', [PrincipalController::class, 'conclusoes'])->name('conclusoes');

Route::get('/principal', [PrincipalController::class, 'principal']);

Route::get('/pagina1', [PrincipalController::class, 'pagina1']);

Route::get('/pagina2', [PrincipalController::class, 'pagina2']);

app/Models/Medicoes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicoes extends Model
{
    use HasFactory;

    public function getResistenciaInternaAttribute()
    {
        return $this->resistencia_carga * ($this->tensao_sem_carga / $this->tensao_com_carga -1);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Medicoes;

class PrincipalController extends Controller {

    public function principalBaterias(){
        return view('principalBaterias');
    }

    public function teoria(){
        return view('teoria');
    }

    public function procedimento(){
        return view('procedimento');
    }

    public function medicoes(){
        $medicoes = Medicoes::all();
        return view('medicoes',compact('medicoes'));
    }

    public function conclusoes(){
        return view('conclusoes');
    }

    public function principal(){
        return view('principal');
    }

    public function pagina1() {
        return view('pagina1');
    }

    public function pagina2() {
        return view('pagina2');
    }

}

resources/views/conclusoes.blade.php
   @extends('templates.base')
   @section('conteudo')
    <main>
        <h1>Conclusões:</h1>
        <hr>
        <p>Por fim, concluímos então que esse trabalho foi de suma importância para nosso aprendizado e que, com certeza, estará presente em nossos futuros projetos.
            Através dessa atividade obtemos um maior conhecimento sobre medições de tensão com carga e sem carga, resistência de pilhas e baterias e cargas elétricas. Aprendemos com maiores detalhes sobre como criar site na web, como personalizar o mesmo e a construir tabelas.
        </p>
        <img class="bateria" src="../imgs/fim.webp"alt="conclusao">
    </main>

    @endsection
    @section('rodape')
       <h4>Rodapé conclusões</h4>
       @endsection

resources/views/medicoes.blade.php
  @extends('templates.base')
  @section('conteudo')
 <main>
        <table class="table table-striped" id="tbDados">
            <thead>
                <tr>
                    <th>Pilha/Bateria</th>
                    <th>tensão nominal (V)</th>
                    <th>Capacidade de corrente (m.A.h)</th>
                    <th>Tensão sem carga(V)</th>
                    <th>Resistência de carga(ohm)</th>
                    <th>Resistência interna(ohm)</th>
                </tr>
            </thead>
            <tbody>
                @foreach($medicoes as $medicao)
                <tr>
                    <td>{{$medicao->pilha_bateria}}</td>
                    <td>{{number_format($medicao->tensao_nominal,1,'.','')}}</td>
                    <td>{{$medicao->capacidade_corrente}}</td>
                    <td>{{$medicao->tensao_sem_carga}}</td>
                    <td>{{$medicao->tensao_com_carga}}</td>
                    <td>{{$medicao->resistencia_carga}}</td>
                    <td>{{number_format($medicao->resistencia_interna,3,'.','')}}</td>
                    </td>
                </tr>
                @endforeach
            </tbody>
            
        </table>

    </main>

    @endsection
    @section('rodape')
       <h4>Rodapé medições</h4>
       @endsection
        

resources/views/pagina1.blade.php
@extends('templates.base')

@section('conteudo')
  <h2>Página 1</h2>
  <hr>  
@endsection


@section('rodape')
 
 <h4>Rodapé da página 1</h4> 
@endsection

resources/views/pagina2.blade.php
@extends('templates.base')

@section('conteudo')
  <h2>Página 2</h2>
  <hr>  
@endsection


@section('rodape')
 
 <h4>Rodapé da página 2</h4> 
@endsection

resources/views/principal.blade.php
@extends('templates.base')

@section('conteudo')
  <h2>Página Principal</h2>
  <hr>  
@endsection


@section('rodape')
 
 <h4>Rodapé da página Principal</h4> 
@endsection

resources/views/principalBaterias.blade.php
    @extends('templates.base')
    @section('conteudo')
    <main>
        <h1>Turma: 2D3 - Grupo 2</h1>
        <h2>Participantes:</h2>
        <hr />  

        <table class="table table-striped table-bordered">
            <tr>
                <th>Matricula</th>
                <th>Nome</th>
                <th>Função</th>
            </tr>
            <tr>
                <th>0072551</th>
                <th>Fernanda</th>
                <th>criação do programa</th>
            </tr>
            <tr>
                <th>0072528</th>
                <th>Ingrid</th>
                <th>criação do programa</th>
            </tr>
            <tr>
                <th>0072525</th>
                <th>Isadora</th>
                <th>criação do programa</th>
            </tr>
            <tr>
                <th>0073006</th>
                <th>Maíra</th>
                <th>criação do programa</th>
            </tr>
            <tr>
                <th>0072549</th>
                <th>Taís</th>
                <th>gerente</th>
            </tr>
        </table>
        <img class="grupo" src="imgs/grupo.webp"grupo">
    </main>

    @endsection
    @section('rodape')
       <h4>Rodapé da pagina principal </h4>
       @endsection

resources/views/procedimento.blade.php
    @extends('templates.base')
    @section('conteudo')
    <main>
        <h1>Procedimentos:</h1>
        <hr>
        <h2>Materiais:</h2>
        <p> 
            Para efetuarmos as mediçoes, utilizamos:
            <p>*1 Multímetro</p>
            <img class="bateria" src="../imgs/multimetro.webp" alt="multimetro">
            <p>*Pilhas </p>
            <img class="bateria" src="../imgs/pilhas.webp" alt="pilhas">
            <p>*Baterias</p>
            <img class="bateria" src="../imgs/baterias.webp" alt="baterias">
            <p>*Resistor de carga</p>
            <img class="bateria" src="../imgs/resistor.webp" alt="resistor">
            <p>*caderno e caneta para anotaçoes</p>
            <img class="bateria" src="../imgs/caderno.webp" alt="caderno">
        </p>


    
        <h3>Mediçoes:</h3>

        <p>Medimos a pilha usando o multímetro na tensão, medindo inicialmente sem o resistor inserido, e depois com o resistor conectado. Esse procedimento é realizado para determinar a resistência interna da pilha.</p>

        <p>Ao medir a tensão da pilha sem o resistor, obtemos o valor da tensão em circuito aberto, ou seja, quando não há corrente fluindo através dela. Em seguida, adicionamos um resistor conhecido ao circuito e medimos novamente a tensão. Ao utilizar o resistor, criamos uma carga no circuito, o que resulta em uma queda de tensão maior do que a medida em circuito aberto.</p>
        <p>Para medir a bateria, seguimos um procedimento semelhante. Primeiro, medimos a tensão da bateria sem qualquer carga ou resistor conectado. Em seguida, adicionamos um resistor conhecido ao circuito e realizamos uma nova medição da tensão. Novamente, a diferença entre as duas leituras de tensão nos permite calcular a corrente que está sendo fornecida pela bateria.

        <p>Esse processo de medição com e sem um resistor é essencial para entender o comportamento da pilha ou bateria em diferentes situações de carga. Ao calcular a resistência interna e a capacidade de fornecer corrente, podemos avaliar o desempenho da pilha ou bateria em diversas aplicações e garantir o seu uso adequado em circuitos elétricos e eletrônicos.</p>
             
        <img class="bateria" src="../imgs/mediçao.webp" alt="medição">
        
    </main>
    
    @endsection
    @section('rodape')
       <h4>Rodapé procedimentos </h4>
       @endsection

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bateriasaravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/estilos.css') }}">
</head>

<body>
    <div class="container-md">
        <h1>Baterias Laravel</h1>
        <hr>
        <nav>
            <ul>
                <li><a href="{{ route('/') }}">Início</a></li>
                <li><a href="{{ route('teoria') }}">Teoria</a></li>
                <li><a href="{{ route('procedimento') }}">Procedimento</a></li>
                <li><a href="{{ route('medicoes') }}">Medições</a></li>
                <li><a href="{{ route('conclusoes') }}">Conclusões</a></li>
            </ul>
        </nav>

        @yield("conteudo")
        <div class="rodape container-md">
            @yield("rodape")
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

resources/views/teoria.blade.php
@extends('templates.base')
@section('conteudo')
 <main>
        <h1>Teoria</h1>
        <hr>
        <h2>Pilhas:</h2>
        <p> 
            Uma pilha é um dispositivo eletroquímico simples, normalmente não recarregável, que consiste em dois eletrodos - um ânodo (eletrodo negativo) e um cátodo (eletrodo positivo) - separados por um eletrólito. Os eletrodos são feitos de materiais diferentes que são selecionados de forma a permitir reações químicas específicas quando a pilha está em uso.
Exemplo:golite
        </p>
        <img class="bateria" src="../imgs/pinha.webp" alt="pinha">
        <h3>Baterias:</h3>
        <p>Uma bateria é um dispositivo eletroquímico semelhante a uma pilha, mas geralmente é composta por várias pilhas conectadas em série ou paralelo para aumentar a capacidade total de armazenamento e fornecimento de energia. Ao contrário das pilhas, as baterias geralmente podem ser recarregadas, o que significa que, após o uso, a energia pode ser restaurada às reações químicas dentro da bateria, permitindo que ela seja usada repetidamente. Exemplo:freedom
        </p>
        <img class="bateria" src="../imgs/bateria.webp" alt="bateria">

        <p>
            
        </p>
    </main>
    @endsection
    @section('rodape')
       <h4>Rodapé Teoria</h4>
       @endsection
 